const SCHEDULES=[
    {
        id:1,
        category:"Cricket",
        image:"https://t4.ftcdn.net/jpg/04/99/62/59/360_F_499625910_ghBBxV9RsHAWLQVPJdTpF49ioBP9ak1Z.jpg",
        teamA:"IIT BHU",
        teamB:"IIT B",
        venue:"Gymkhana Ground",
        time:"7:00 PM",
    },
    {
        id:2,
        category:"Football",
        image:"https://previews.123rf.com/images/wannen19/wannen191809/wannen19180900001/108328429-football-logo-designs.jpg",
        teamA:"IIT BHU",
        teamB:"IIT Roorkee",
        venue:"Gymkhana Ground",
        time:"5:00 PM",
    },
    {
        id:3,
        category:"Basketball",
        image:"https://png.pngtree.com/png-vector/20191027/ourmid/pngtree-basketball-championship-logo-modern-professional-basketball-logo-design-png-image_1855709.jpg",
        teamA:"IIT BHU",
        teamB:"IIT Guwahati",
        venue:"Rajputana Ground",
        time:"6:00 PM",
    },
    {
        id:4,
        category:"Cricket",
        image:"https://t4.ftcdn.net/jpg/04/99/62/59/360_F_499625910_ghBBxV9RsHAWLQVPJdTpF49ioBP9ak1Z.jpg",
        teamA:"IIT Delhi",
        teamB:"IIT Goa",
        venue:"ADV Ground",
        time:"4:00 PM",
    },
    {
        id:5,
        category:"Basketball",
        image:"https://png.pngtree.com/png-vector/20191027/ourmid/pngtree-basketball-championship-logo-modern-professional-basketball-logo-design-png-image_1855709.jpg",
        teamA:"IIT Hyderabad",
        teamB:"IIT Mandi",
        venue:"Rajputana Ground",
        time:"8:00 PM",
    },
    {
        id:6,
        category:"Hockey",
        image:"https://thumbs.dreamstime.com/z/hockey-logo-template-player-hockey-vector-design-illustration-hockey-player-hockey-logo-template-player-hockey-vector-design-170458615.jpg",
        teamA:"IIT BHU",
        teamB:"IIT Dhanbad",
        venue:"Gymkhana Ground",
        time:"7:00 PM",
    },
    {
        id:7,
        category:"Football",
        image:"https://previews.123rf.com/images/wannen19/wannen191809/wannen19180900001/108328429-football-logo-designs.jpg",
        teamA:"IIT Jodhpur",
        teamB:"IIT Madras",
        venue:"ADV Ground",
        time:"3:00 PM",
    },
    {
        id:8,
        category:"Cricket",
        image:"https://t4.ftcdn.net/jpg/04/99/62/59/360_F_499625910_ghBBxV9RsHAWLQVPJdTpF49ioBP9ak1Z.jpg",
        teamA:"IIT Gnadhinagar",
        teamB:"IIT BHU",
        venue:"Rajputana Ground",
        time:"6:00 PM",
    }
];

export default SCHEDULES;